
package com.gupao.webservice.api.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SayGoodImpl", targetNamespace = "http://impl.api.webservice.gupao.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SayGoodImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayGood", targetNamespace = "http://impl.api.webservice.gupao.com/", className = "com.gupao.webservice.api.impl.SayGood")
    @ResponseWrapper(localName = "sayGoodResponse", targetNamespace = "http://impl.api.webservice.gupao.com/", className = "com.gupao.webservice.api.impl.SayGoodResponse")
    @Action(input = "http://impl.api.webservice.gupao.com/SayGoodImpl/sayGoodRequest", output = "http://impl.api.webservice.gupao.com/SayGoodImpl/sayGoodResponse")
    public String sayGood(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
