
package com.gupao.webservice.api.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SayGoodImplService", targetNamespace = "http://impl.api.webservice.gupao.com/", wsdlLocation = "http://localhost:8000/api/say?wsdl")
public class SayGoodImplService
    extends Service
{

    private final static URL SAYGOODIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SAYGOODIMPLSERVICE_EXCEPTION;
    private final static QName SAYGOODIMPLSERVICE_QNAME = new QName("http://impl.api.webservice.gupao.com/", "SayGoodImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8000/api/say?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SAYGOODIMPLSERVICE_WSDL_LOCATION = url;
        SAYGOODIMPLSERVICE_EXCEPTION = e;
    }

    public SayGoodImplService() {
        super(__getWsdlLocation(), SAYGOODIMPLSERVICE_QNAME);
    }

    public SayGoodImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SAYGOODIMPLSERVICE_QNAME, features);
    }

    public SayGoodImplService(URL wsdlLocation) {
        super(wsdlLocation, SAYGOODIMPLSERVICE_QNAME);
    }

    public SayGoodImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SAYGOODIMPLSERVICE_QNAME, features);
    }

    public SayGoodImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SayGoodImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SayGoodImpl
     */
    @WebEndpoint(name = "SayGoodImplPort")
    public SayGoodImpl getSayGoodImplPort() {
        return super.getPort(new QName("http://impl.api.webservice.gupao.com/", "SayGoodImplPort"), SayGoodImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SayGoodImpl
     */
    @WebEndpoint(name = "SayGoodImplPort")
    public SayGoodImpl getSayGoodImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.api.webservice.gupao.com/", "SayGoodImplPort"), SayGoodImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SAYGOODIMPLSERVICE_EXCEPTION!= null) {
            throw SAYGOODIMPLSERVICE_EXCEPTION;
        }
        return SAYGOODIMPLSERVICE_WSDL_LOCATION;
    }

}
